services:
  proxy: # proxy directory
    image: nginx
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 80:80
    depends_on:
      - backend

  backend: # backend directory
    build:
      context: backend 
      target: builder # references builder stage in multi-stage build in Dockerfile

